site_name: Inex OPC Server
repo_url: https://github.com/inex-dev/opc-server-doc.git

plugins:
    - search:
        lang: [ru, en]

theme:
    name: 'material'
    language: 'ru'

extra:
    search:
        language: 'en, de, ru'
        
markdown_extensions:
    - codehilite
    - admonition