site_name: Inex OPC сервер

nav:
    - Введение: index.md
    - Установка и настройка Inex OPC сервера: install-and-settings.md
    - Подключение МЭК104: conf-iec104.md
    - Разработка источников данных:
        - Справка по API: 
            - Интерфейсы: api-references-interfaces.md
            - Классы: api-references-classes.md
            - Структуры: api-references-structs.md
            - Перечисления: api-references-enums.md
        - Пример источника данных: sample-ds.md

plugins:
    - search:
        lang: [ru, en]

theme:
    name: 'material'
    language: 'ru'

extra:
    search:
        language: 'en, de, ru'

markdown_extensions:
    - codehilite
    - admonition