site_name: Inex OPC сервер

nav:
    - Введение: index.md
    - Установка и настройка Inex OPC сервера: install-and-settings.md

plugins:
    - search:
        lang: [ru, en]

theme:
    name: 'material'
    language: 'ru'

extra:
    search:
        language: 'en, de, ru'

markdown_extensions:
    - codehilite
    - admonition